### ISSUE TITLE
Error getting room info

### ISSUE THREAD

**Issue by Vleerian** [Atagait/DrrrAsync#13]
An error occurs when getting room info, causing the bot to fail.
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DrrrAsyncBot.Objects.DrrrRoom..ctor(JObject RoomObject) in F:\Programming\Durarara Projects\WelneZodiv\DurararaAsync\Objects\DrrrRoom.cs:line 69
   at DrrrAsyncBot.Core.DrrrClient.GetLounge() in F:\Programming\Durarara Projects\WelneZodiv\DurararaAsync\Core\DrrrClient.cs:line 113
   at DrrrAsyncBot.Bot.DrrrBot.Run() in F:\Programming\Durarara Projects\WelneZodiv\DurararaAsync\Bot\Bot.cs:line 171
   at WelneZodiv.Program.Run() in F:\Programming\Durarara Projects\WelneZodiv\WelneZodiv\Program.cs:line 42
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WelneZodiv.Program..ctor() in F:\Programming\Durarara Projects\WelneZodiv\WelneZodiv\Program.cs:line 58 --- One or more errors occurred. (Object reference not set to an instance of an object.)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WelneZodiv.Program..ctor() in F:\Programming\Durarara Projects\WelneZodiv\WelneZodiv\Program.cs:line 58
```
It appears to be in the DrrrRoom constructor that uses a JObject, and seems to be caused in the GetLounge() function.

This doesn't seem to be an error presently; It may be caused by malformed data on the Lounge API endpoint. I currently can't reproduce it, so this will just be here for posterity's sake.

**Comment by Vleerian** [comment]
The issue seemed to be caused by the existence of "Game Rooms." They're exceedingly rare and appear to be static - lacking a host. I added a check to this in DrrrRoom.cs
